### ISSUE TITLE
implement `std::error::Error` for `aead::Error`

### ISSUE THREAD

**Issue by s97712** [RustCrypto/AEADs#124]
`aead::Error` doesn't implement `std::error::Error`, then can't work with some error library such as `fail`, `anyhow`
consider implement `std::error::Error` for `aead::Error`?

**Comment by tarcieri** [comment]
That was added here:

https://github.com/RustCrypto/traits/pull/63

...unfortunately I don't have access to release the `aead` crate

**Comment by newpavlov** [comment]
This issue is fixed in `aead v0.3`.

**Comment by jhpratt** [comment]
@tarcieri Is it possible to add a `std` feature to the various reverse dependencies? I'm using `aes_gcm_siv`, and am currently having to pull in `aead` as a direct dependency just to enable the feature.
