### ISSUE TITLE
Stream data to cipher

### ISSUE THREAD

**Issue by acasajus** [RustCrypto/AEADs#132]
Hello,

 Is it possible to stream in data to cipher to avoid having to have all the data in memory to pass it though the AEAD? Something like (in pseudocode)

```
 aead = AEAD::new(mode, nonce)
 while plaindata = plainfile.read(1024) {
  cipherfile.write(aead.encrypt(plaindata))
}
cipherfile.write(aead.close_and_flush())
```

How could I do this if the file is several gigs in size and I don't have that much mem?

Thanks in advance,

**Comment by tarcieri** [comment]
Streaming *encryption* like this is possible with some AEAD modes, depending on how the algorithm is structured. It requires a single-pass construction that places things like the AAD and plaintext length at the end of the MAC input.

Note that streaming decryption which exposes candidate plaintexts without first checking the MAC tag is inherently unsafe.

The general security framework for this concept I prefer for solving this particular problem [Online Authenticated Encryption (OAE)](https://web.cs.ucdavis.edu/~rogaway/papers/oae.pdf) and within that framework there are two provably secure schemes for this developed by Phil Rogaway et al, one of which I've implemented in [Miscreant](https://miscreant.io/) which is the predecessor of the `aes-siv` crate:

- [STREAM](https://github.com/miscreant/meta/wiki/STREAM): provides nonce-based online authenticated encryption (nOAE), a segmented/streaming AEAD scheme
- [CHAIN](https://github.com/miscreant/meta/issues/33): (mentioned in the aforementioned paper) requires an MRAE cipher but provides a stronger notion of security called OAE2 which provably guarantees a sequence of AEAD messages was encrypted/decrypted in-order

Note that [`STREAM` is presently implemented in Miscreant](https://docs.rs/miscreant/0.4.2/miscreant/stream/index.html). It might be interesting to upstream its implementation somewhere in the RustCrypto project, which is something I've considered in the past but haven't actually done yet.

**Comment by acasajus** [comment]
Thanks for the comprehensive response. I'll take a look at [Miscreant](https://miscreant.io/) :+1:

**Comment by tarcieri** [comment]
As of `aead` v0.4 there is now an [`aead::stream`](https://docs.rs/aead/latest/aead/stream/index.html) module.
