### ISSUE TITLE
Move ring-aead into a separate repository?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/AEADs#154]
RustCrypto is generally for pure-Rust implementations, so `ring-aead` looks a bit out of place. We already have `asm-hashes`, so we are not completely puristic in this regard. Thus how about moving the crate into a separate repository? In future, if someone will be interested, we may add wrapper crates for other algorithm families as well.

**Comment by tarcieri** [comment]
Happy to do whatever with it. It doesn't seem to have gotten any uptake.

Related: https://github.com/RustCrypto/hashes/pull/82
