### ISSUE TITLE
Do not depend on criterion for benchmarks by default?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/AEADs#183]
Criterion has a sizable dependency tree, which significantly increases compilation time of tests. I think at the very least we should make criterion benchmarks optional and disabled by default.

**Comment by tarcieri** [comment]
I agree. They’re really useful for tuning, but otherwise cumbersome.

One approach I think might be helpful is factoring benchmarks out into a crate (e.g. a ‘benches’ crate per repo)
