### ISSUE TITLE
Any aes256-gcm example without nonce?

### ISSUE THREAD

**Issue by tr1ox1dev** [RustCrypto/AEADs#211]
**Hi. Anyone knows how to do crypt of text without nonce, just with key and text? Thanks if you will tell me** :heart:

**Comment by newpavlov** [comment]
If your key is longer than 32 bytes, then probably it's concatenated key and nonce. Otherwise try nonce filled with zeros.

This is not a correct place for general cryptography-related questions, so I am gonna close this issue.
