### ISSUE TITLE
Feature request: authenticate without encrypting

### ISSUE THREAD

**Issue by hardcore-sushi** [RustCrypto/AEADs#240]
Hi !
I would like to build a network protocol secured by AES GCM. I have to send the length of the payload before the payload itself so that the receiver knows how much data he should expect in the transmission. With your implementation, the problem is, as far as I know, I can't authenticate data without encrypting. I saw that the python PyCryptodome lib can do this with the AES.update() method. Does your lib provide such a method ?
If not, what can I do ? Do you plan to implement this method ?

Thanks

**Comment by tarcieri** [comment]
Authentication without encryption is possible by using an AEAD message's additional associated data.

If you're using the [`AeadInPlace`](https://docs.rs/aead/latest/aead/trait.AeadInPlace.html) API, it's the `associated_data` parameter.

If you're using the [`Aead`](https://docs.rs/aead/latest/aead/trait.Aead.html), you'll need to construct a [`Payload`](https://docs.rs/aead/latest/aead/struct.Payload.html) to be passed to the message, placing associated data in the `aad` field.

**Comment by hardcore-sushi** [comment]
Oh, I didn't know about the Payload struct.
Now it works ! Thank you.

**Comment by newpavlov** [comment]
Also note that we have a separate repository for [MAC](https://github.com/RustCrypto/MACs) algorithms.
