### ISSUE TITLE
crypto_box rand version is lagging

### ISSUE THREAD

**Issue by anthonyjmartinez** [RustCrypto/AEADs#271]
`rand` 0.8.0 breaks the `crypto_box` examples.

This could potentially be resolved with `pub extern crate rand` to remove any ambiguity with the `rand` versioning and allow for `let mut rng = crypto_box::rand::thread_rng();`

blocked PRs from depend bot show the same errors I encountered myself, so I won't regurgitate them here.

**Comment by tarcieri** [comment]
This upgrade is dependent on a corresponding upgrade to `x25519-dalek`. See: https://github.com/dalek-cryptography/x25519-dalek/pull/64

Note that we use `rand_core` both because we don't need anything `rand`-specific and for supporting `no_std`.

**Comment by tarcieri** [comment]
Fixed in #292
