### ISSUE TITLE
Traits in `ccm` are private

### ISSUE THREAD

**Issue by datdenkikniet** [RustCrypto/AEADs#278]
Hi,

I think it's intentional, but the traits in the ccm crate (i.e. [this file](https://github.com/RustCrypto/AEADs/blob/master/ccm/src/traits.rs)) are private since the module they're in is not reexported in lib.rs. 

I'd like to implement a function that is generic over CCMs, but would have to implement structs for each size, either manually or with a macro since I cannot use the traits to constrain my generics.

Is there any way around this?

Kind regards,

Jona

**Comment by tarcieri** [comment]
This does seem problematic.

@newpavlov do we really need sealed traits for this? It seems like it wouldn't be possible for someone to add an impl of these traits in a problematic way, or at least, if they were to do that they'd really have to go out of their way to do so (e.g. create their own fake `typenum` type)

**Comment by newpavlov** [comment]
CCM is defined only for the specified sizes, so I think that the sealed trait approach is a correct one in this case. But I agree that inability of being generic over tag size is an oversight. I think we should follow the `byteorder` example here, i.e. introduce a public trait bounded by a sealed trait. In `byteorder`'s case it's [`ByteOrder`](https://docs.rs/byteorder/1.4.3/byteorder/trait.ByteOrder.html) and `Sealed` traits respectively.
