### ISSUE TITLE
xsalsa20poly1305's rand_core dependency is outdated

### ISSUE THREAD

**Issue by piegamesde** [RustCrypto/AEADs#279]
This is similar to #271, but as far as I can tell should be resolvable independently.

**Comment by tarcieri** [comment]
Yes, it could be updated independently, however the `xsalsa20poly1305::generate_nonce` function, which uses `rand_core`, is re-exported as part of the `crypto_box` API, which makes it slightly troublesome to update them separately.

It would at least break the doctests for `crypto_box` to do so, but those could be temporarily disabled in CI.

That said, I'm hopeful https://github.com/dalek-cryptography/x25519-dalek/pull/64 might get addressed soon and we can do a coordinated upgrade.

**Comment by tarcieri** [comment]
Fixed in #292
