### ISSUE TITLE
MSRV in Readme is outdated

### ISSUE THREAD

**Issue by piegamesde** [RustCrypto/AEADs#301]
https://github.com/RustCrypto/AEADs#minimum-supported-rust-version vs https://github.com/RustCrypto/AEADs/blob/master/.github/workflows/xsalsa20poly1305.yml#L45

**Comment by tarcieri** [comment]
Thanks. We should probably remove the repo-level MSRV since we aren't really coordinating a global MSRV anymore.

**Comment by piegamesde** [comment]
Yes. I've found that the best way to track MSRV is CI: if it fails, open the repo of the failing dependency, and look what they use as MSRV.
