### ISSUE TITLE
Security of MGM

### ISSUE THREAD

**Issue by ethindp** [RustCrypto/AEADs#325]
Apologies if this isn't the right place to ask this kind of thing, but I'm wondering precisely how secure MGM is? My research of it couldn't dig up anything about any audits that have been done on the algorithm or whether using it has any security implications. From my understanding of the paper it appears to be a cipher combinator of sorts, but I'm not an expert in crypto and since I'm blind the math in the paper was difficult to comprehend since its in a PDF and math never renders well in PDFs.
Can someone outline the security of the algorithm and when it would be beneficial to use?

**Comment by tarcieri** [comment]
I'm personally not very familiar with it, but here's a paper:

https://eprint.iacr.org/2019/123.pdf

I think the main reason you'd use it is because it's the AEAD mode used by the GOST State Standardization System.

In general, I'd probably recommend `aes-gcm`, `aes-gcm-siv`, or `chacha20poly1305`.

**Comment by ethindp** [comment]
@tarcieri I similarly would use AES-GCM/AES-GCM-SIV/ChaCha20/XChaCha20. I was just wondering if MGM truly had any security benefits. The paper you linked to was the same one I found and I couldn't really get much out of it.

**Comment by newpavlov** [comment]
IIUC the mode developers claim that it has some theoretical benefits over GCM, but I think that from practical perspective resistance to nonce-misuse provided by SIV modes easily beats those, so I would also recommend to use those instead if for your use-case their performance is sufficient.
