### ISSUE TITLE
crypto_box: move into a separate repository?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/AEADs#338]
The `crypto_box` crate feels a bit out of place in this repository since it includes bits of public key cryptography.

It could be worth to move it into a separate repository. We could dedicate this repository to emulation of NaCl/libsodium APIs using our crates as a pure-Rust backend. In a certain sense it will be like [`ring-compat`](https://github.com/RustCrypto/ring-compat/), but in reverse.

**Comment by newpavlov** [comment]
@tarcieri 
Regarding potential name for the repository, how about `libsodium-compat`?

**Comment by tarcieri** [comment]
For `crypto_box` in particular I'd suggest something more like `nacl-compat`, as the construction can be found in the original NaCl and all NaCl forks, including libsodium and TweetNaCl.

If we had that, it might make sense to move `xsalsa20poly1305` there too, as it isn't technically an AEAD mode.

**Comment by newpavlov** [comment]
`nacl-compat` sounds good to me as well!

>If we had that, it might make sense to move xsalsa20poly1305 there too, as it isn't technically an AEAD mode.

Well, we could say this repo is for AE(AD) algorithms. :) Considering that AE traits (may be added)[https://github.com/RustCrypto/traits/issues/261] to the `aead` crate, I think it's fine to keep it here. Although I plan to introduce one day a separate folder for "combination" crates, which would be convenience thin wrappers around other crates.
