### ISSUE TITLE
EAX unique nonce issue

### ISSUE THREAD

**Issue by STashakkori** [RustCrypto/AEADs#372]
EAX seems to only work if the same nonce is used between encryption and decryption, which defeats the purpose of a nonce. Using same nonce it works. Using different (uniquely generated) nonce I get the following:  aead::Error

Please assist. Thank you

**Comment by tarcieri** [comment]
Encryption and decryption always require the same nonce. If you use a different nonce from what you encrypted with during encryption, an `aead::Error` is expected and desirable.

The important detail is to not reuse nonces when encrypting. Never encrypt more than one message under a given nonce.
