### ISSUE TITLE
Outdated version of zeroize forced in aes-gcm-siv

### ISSUE THREAD

**Issue by mervyn-mccreight** [RustCrypto/AEADs#377]
Currently the version of `zeroize` is required to be `< 1.4` which conflicts with the latest version of [secrecy](https://docs.rs/secrecy/latest/secrecy/), which needs `zeroice` to be `>= 1.4`.

Is there a reason why `zeroize` is explicitly needed in that version, or can it be updated?

**Comment by tarcieri** [comment]
It's a hack to preserve the current MSRV.

I agree it's less than ideal. Unfortunately Rust does not provide other mechanisms to select MSRV-compatible packages yet.

**Comment by mervyn-mccreight** [comment]
Ah I see, thanks. 
Is being compatible to Rust `< 1.51` a strict requirement, or is it something that is open to change?

**Comment by tarcieri** [comment]
We should definitely bump MSRV soon. Now that the 2021 edition is out, it would probably be good to bump all of our crates.

One of the many things the 2021 edition helps with is having a `rust-version` crate attribute which helps sort out MSRV-related issues like this.

**Comment by newpavlov** [comment]
>Is being compatible to Rust < 1.51 a strict requirement

It's not, but we consider bumping MSRV being a breaking change.

Regarding `rust-version`, I don't think that until https://github.com/rust-lang/cargo/issues/9930 gets implemented we should change our [MSRV policy](https://github.com/RustCrypto/AEADs#msrv-policy).

**Comment by mervyn-mccreight** [comment]
Thanks for the detailed explanation :)

Are PRs to bump the version of `zeroice` plus increasing the defined `MSRV` welcome, or do you think that this may not be a good "first issue"?

**Comment by tarcieri** [comment]
For something like an edition bump, it'd be nice to do in a coordinated manner across crates/repos

**Comment by fjarri** [comment]
Since this issue is still open, how about bumping `zeroize` to 1.5 (so that it doesn't conflict with the new `elliptic-curves`, and, I assume, other RustCrypto crates as well)?

**Comment by tarcieri** [comment]
@fjarri it's going to be a giant pain, since we need to do coordinated bumps of all of the dependencies

**Comment by newpavlov** [comment]
`cipher` itself does not depend on `zeroize`, so I think we can simply bump MSRV for implementation crates during migration to `cipher v0.4`.

**Comment by tarcieri** [comment]
FYI: I've opened a tracking issue for `zeroize` version compatibility here: https://github.com/RustCrypto/utils/issues/723

**Comment by tarcieri** [comment]
I've released `aes-gcm-siv` v0.11.0-pre with an unpinned `zeroize`, which should unblock people who are stuck on compatibility.

Please see #410 for additional upgrades needed for a final release.
