### ISSUE TITLE
aes-gcm: Allow variable sized nonce at runtime

### ISSUE THREAD

**Issue by littledivy** [RustCrypto/AEADs#389]
In Deno, WebCrypto nonces are coming from JavaScript at runtime and so generic compile-time nonces are not possible without setting a restriction on the user (Some packages in the Node ecosystem like `cryptr` use 128bit IVs instead of 96bit).

It would be nice to have a non-`generic-array` based API for use cases like this :-)

**Comment by RihardNovozhilov** [comment]
Do you have any solution for this?

**Comment by tarcieri** [comment]
It's a feature we can potentially look at adding. PRs accepted.

In the meantime I'd suggest supporting 96-bit and 128-bit IVs and returning an error on others. I think in practice you shouldn't encounter much real-world usage outside of those two.

**Comment by newpavlov** [comment]
I will try to add such functionality in `aead v0.5`.

**Comment by tarcieri** [comment]
@newpavlov I'm not sure it's generally useful. AES-GCM is pretty unique in terms of having variable nonce size, and if anything it's a misfeature, not a pattern to be replicated.

**Comment by KaKi87** [comment]
It is useful to be compatible with a Node lib than has 50k+ installs per week.

**Comment by littledivy** [comment]
I agree with @tarcieri being able to specify variable nonce size (it can be up to 2^64-1 bytes long) is a misfeature in WebCrypto.

> It is useful to be compatible with a Node lib that has 50k+ installs per week.

I don't think this compatibility should be enforced on a Rust crate :-) For Deno, we've just added 128bit nonce support alongside 96bit for now.

**Comment by KaKi87** [comment]
> I don't think this compatibility should be enforced on a Rust crate :-) For Deno, we've just added 128bit nonce support alongside 96bit for now.

Ah, I thought Deno's issue was depending on this one :sweat_smile: My bad. Thanks

**Comment by sfackler** [comment]
@tarcieri I may tackle this - does this seem like a reasonable approach?

* Remove the nonce size parameter from `AesGcm`. The `AeadCore::NonceSize` associated type is always `U12`.
* Add `encrypt_in_place_detached_with_nonce_slice` and `decrypt_in_place_detached_with_nonce_slice` methods that take slices rather than `GenericArray`s in for the nonce. The `encrypt_in_place_detached` and `decrypt_in_place_detached` methods delegate to those.

We could also add `_with_nonce_slice` variants of all of the other `AeadInPlace` and `Aead` methods but I don't know how common a nonstandard nonce is, so it may not be worth it.

**Comment by tarcieri** [comment]
> Remove the nonce size parameter from AesGcm. The AeadCore::NonceSize associated type is always U12.

This not only abandons type safety for the nonce size but signals the wrong nonce size via the type system. That’s just broken.

Taking a step back: from a practical perspective do you really need to support nonce sizes other than 12 and 16?

**Comment by sfackler** [comment]
In my particular instance I need to interact with an existing thing that uses 32 byte nonces in a legacy context and normal 12 byte nonces in the current mode. It's not a huge problem to just use separate instantiations of `AesGcm` for 12 and 32 bytes, but it makes the code more annoying than it'd have to be if I could just use a slice for the nonce buffer.

Is your [earlier comment](https://github.com/RustCrypto/AEADs/issues/389#issuecomment-1053727469) no longer correct? If the type is going to support runtime-specified nonce lengths, then it by definition can't encode that dynamic length in the type system. Unless the proposal would be to not implement the Aead traits at all?

**Comment by tarcieri** [comment]
It would require a separate construction that doesn't support the standard `aead` traits, correct.

But the more I've thought about this problem, the less it seems worth supporting and the more it seems like it would introduce runtime errors that don't need to exist.

Nobody is using a high cardinality of nonce sizes: it seems most people support two at most. So monomorphizing the code twice for a couple different nonce sizes does not seem to be a considerable burden worth introducing a separate, non-type-safe API for.
