### ISSUE TITLE
ChaCha20Poly1305 doesn't build with 'heapless' enabled when targetting riscv32i-unknown-none-elf

### ISSUE THREAD

**Issue by Kriskras99** [RustCrypto/AEADs#398]
When I add ChaCha20Poly1305 (version 0.9.0) as a dependency:
```toml
[dependencies]
chacha20poly1305 = { version = "0.9.0", features = ["heapless"] }
```
and include it in the code (`use chacha20poly1305`) I get the following error:
```
   Compiling heapless v0.7.10
error[E0432]: unresolved import `atomic_polyfill`
  --> /home/kriskras99/.cargo/registry/src/github.com-1ecc6299db9ec823/heapless-0.7.10/src/spsc.rs:90:5
   |
90 | use atomic_polyfill::{AtomicUsize, Ordering};
   |     ^^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_polyfill`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `heapless` due to previous error
```
I think something is going wrong with heapless' features, but I'm not entirely sure.
I made [an MVP repo](https://github.com/Kriskras99/rust-crypto-unbuildable) where you can reproduce the issue by executing `cargo build` (assuming you have the riscv32i-unknown-none-elf target installed).

**Comment by tarcieri** [comment]
Yeah, this looks like a bug in `heapless`. Have you reported it upstream?

**Comment by Kriskras99** [comment]
I don't think it's a bug in `heapless`, if I include that without ChaCha20Poly8 ([see repository](https://github.com/Kriskras99/rust-crypto-unbuildable/tree/heapless), it compiles just fine.
If I add `heapless` and `chacha20poly8` at the same time:
```toml
[dependencies]
chacha20poly1305 = { version = "0.9.0", features = ["heapless"] }
heapless = "0.7"
```
then I get:
```
   Compiling unbuildable_mvp v0.1.0 (/home/kriskras99/Source/unbuildable_mvp)
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait

warning: unused import: `chacha20poly1305`
 --> src/main.rs:5:5
  |
5 | use chacha20poly1305;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: `#[alloc_error_handler]` function required, but not found

note: use `#![feature(default_alloc_error_handler)]` for a default error handler

warning: `unbuildable_mvp` (bin "unbuildable_mvp") generated 1 warning
error: could not compile `unbuildable_mvp` due to 2 previous errors; 1 warning emitted
```
So then it somehow needs an allocator?

**Comment by tarcieri** [comment]
Include `chacha20poly1305` with the following in your Cargo.toml:

```toml
[dependencies]
chacha20poly1305 = { version = "0.9.0", default-features = false, features = ["heapless"] }
```

...and see if that addresses your problem.

**Comment by tarcieri** [comment]
The `aead` crate includes `heapless` without default features:

https://github.com/RustCrypto/traits/blob/master/aead/Cargo.toml#L23

If you're seeing errors like this:

```
   Compiling heapless v0.7.10
error[E0432]: unresolved import `atomic_polyfill`
  --> /home/kriskras99/.cargo/registry/src/github.com-1ecc6299db9ec823/heapless-0.7.10/src/spsc.rs:90:5
   |
90 | use atomic_polyfill::{AtomicUsize, Ordering};
   |     ^^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_polyfill`
```

...it sounds like there's been a regression in `heapless` such that it's no longer able to build without default features.

**Comment by Kriskras99** [comment]
I'll submit an issue upstream. Thanks!
