### ISSUE TITLE
Release a new version of `chacha20poly1305` now that `zeroize` is not blocked to `<1.5`

### ISSUE THREAD

**Issue by poliorcetics** [RustCrypto/AEADs#400]
Without this, it is not possible to use this crate in the same dependency tree as https://github.com/RustCrypto/RSA since it has `num-bigint-dig v0.8.1` which needs `zeroize >= 1.5`

**Comment by poliorcetics** [comment]
This also needs to update the dependency on `chacha20` to version `0.9.0` at least

**Comment by tarcieri** [comment]
See the master tracking issue here: https://github.com/RustCrypto/utils/issues/723

**Comment by poliorcetics** [comment]
I think everything has been updated, a new version should be published to make it available to people using crates.io

**Comment by tarcieri** [comment]
I can cut a prerelease if that's helpful. However, the next final release with a minor version bump would ideally include [a new release of `poly1305` based on `universal-hash` v0.5](https://github.com/RustCrypto/universal-hashes/pull/148)

**Comment by tarcieri** [comment]
I cut a v0.10.0-pre release: #406 

We'll hopefully have a final release out soon
