### ISSUE TITLE
LLVM Error building for x86_64-unknown-uefi

### ISSUE THREAD

**Issue by sven-eliasen** [RustCrypto/AEADs#405]
Hi guys,

EDIT: I read myself and wanted to add that I tried this with every of these AEAD crates.

I would need some building for the following target : `x86_64-unknown-uefi`, and in `no-std` environment.

Building the crate doesn't seems to be the problem, but when I instantiate a `cipher`, like this :
```rust
let key = Key::from(key_bytes);
let cipher = Aes256Gcm::new(&key);
```
I get this LLVM error : 
`LLVM ERROR: Do not know how to split the result of this operator!`

I don't really have much knowledge about LLVM so I don't really know where to start.

I tried with the following environement variable : 
`RUSTFLAGS="-Ctarget-cpu=sandybridge -Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3"`

But it makes the core library build fail.

**Comment by tarcieri** [comment]
One thing you could try to help narrow down the problem is enabling the `force-soft` feature.

Those CPU flags should be sufficient to force AES-NI and skip runtime autodetection. But is AES-NI actually available from UEFI?

**Comment by tarcieri** [comment]
I'm talking about the `aes-gcm/force-soft` crate feature, not a target feature

**Comment by sven-eliasen** [comment]
Oh right...

Well that's it, it works !
Sorry if it was written somewhere about this kind of issue.

**Comment by tarcieri** [comment]
I think you're the first / among the first to try building this crate for a UEFI target.

It'd be interesting to know why AES-NI isn't working, or if AES-NI is even usable from UEFI in general.

**Comment by newpavlov** [comment]
It looks like the UEFI target has issues with SIMD intrinsics in general, not only with AES-NI. The same issue has happened with `rand_chacha` as well. But since in `getrandom` the RDRAND intrinsic works fine, it may be somehow related to use of XMM registers.

As I suggested earlier, I think you should report this error to the [rust-lang/rust](https://github.com/rust-lang/rust) repository.
