### ISSUE TITLE
aes-gcm-siv: outdated aes and cipher

### ISSUE THREAD

**Issue by tomtau** [RustCrypto/AEADs#410]
good to bump the crate versions (as in https://github.com/RustCrypto/AEADs/pull/409 for aes-gcm)

**Comment by tarcieri** [comment]
Will get to this soon. Recently updated `aes-gcm` and `chacha20poly1305`.

**Comment by rozbb** [comment]
I began an attempt at this and encountered a problem: `ParBlocksSizeUser` is not implemented for `Aes128`. In fact, `ParBlocksSizeUser` is only implemented for [hidden backend types](https://github.com/RustCrypto/block-ciphers/blob/master/aes/src/soft.rs#L254=) throughout the AEADs repo. I think this has to change before anything else happens.

Once that's fixed, my branch [here](https://github.com/rozbb/AEADs/tree/update-cipher) should be mergeable.

**Comment by rozbb** [comment]
It doesn’t look like aes-gcm does interleaved/parallel decryption, whereas aes-gcm-siv currently does. Is that right?

**Comment by tarcieri** [comment]
You're right, that is different

**Comment by rozbb** [comment]
See above PR. I have a [branch](https://github.com/rozbb/AEADs/tree/update-cipher) that successfully updates the dependencies of `aes-gcm-siv`. Just need a new version of `block-ciphers`.

**Comment by tomtau** [comment]
it seems fixed in 0.11 https://github.com/RustCrypto/AEADs/pull/464
