### ISSUE TITLE
Publish new version of `aes-gcm` to get access to updated deps (notably `aes 0.8` / `cipher 0.4`)

### ISSUE THREAD

**Issue by poliorcetics** [RustCrypto/AEADs#411]
Is there work to do before publishing a new version ?

**Comment by tarcieri** [comment]
Yes, we're going to update `universal-hash` to v0.5: https://github.com/RustCrypto/traits/pull/965

...and likely release a new version of `aead` as well.

In the meantime I can publish a prerelease.

**Comment by tarcieri** [comment]
I released `aes-gcm` v0.10.0-pre (#413)

**Comment by poliorcetics** [comment]
Thanks a lot !

**Comment by tarcieri** [comment]
Released in #456
