### ISSUE TITLE
Make zeroize's version more compatible

### ISSUE THREAD

**Issue by lei2022** [RustCrypto/AEADs#416]
As seen in "aes-gcm-siv/Cargo.toml", zeroize is a dependency and has a hard requirement of ">=1, <1.4": { version = ">=1, <1.4", default-features = false }. It is not compatible with versions >= 1.5. Please consider making it "zeroize = { version = "1", default-features = false }" so it is more compatible.

The latest zeroize version as of this Issue is https://crates.io/crates/zeroize/1.5.4

**Comment by tarcieri** [comment]
Dup of #377 

See also: https://github.com/RustCrypto/utils/issues/723
