### ISSUE TITLE
Usage sample for aes-gsm on docs.rs doesn't compile for me

### ISSUE THREAD

**Issue by itsTyrion** [RustCrypto/AEADs#418]
A simple program with just `fn main()` and the "usage" snippet [from docs.rs](https://docs.rs/aes-gcm/latest/aes_gcm/#usage) throws this error for me:
```error[E0284]: type annotations needed: cannot satisfy `<_ as KeySizeUser>::KeySize == UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>`
 --> src\main.rs:7:15
  |
7 |     let key = Key::from_slice(b"an example very very secret key.");
  |               ^^^ cannot satisfy `<_ as KeySizeUser>::KeySize == UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>`
```
After replacing `Key` with `aes_gcm::aead::generic_array::GenericArray`, it seems to work fine.
What am I missing here?

**Comment by tarcieri** [comment]
The docs are for the latest release: v0.9.4.

It looks like you're using v0.10.0-pre? If so, here are the docs for that:

https://docs.rs/aes-gcm/0.10.0-pre/aes_gcm/index.html#usage

Note that the docs are tested by rustdoc and guaranteed to compile, so I'm guessing the version difference is your issue. Closing this.

**Comment by itsTyrion** [comment]
whoops, missed the -pre part. Thanks for the super fast response.^^ It was the different version
