### ISSUE TITLE
help for rust beginner

### ISSUE THREAD

**Issue by Antidote1911** [RustCrypto/AEADs#421]
For my file encryptor [Cryptyrust](https://github.com/Antidote1911/cryptyrust), I am trying to add the choice between Aes256GcmSiv or XChaCha20Poly1305 but I don't know the good method. I am trying with enums, Box, ... but can't find a working method.

```rust
let test=1;

    let aead = match test{
        1 => XChaCha20Poly1305::new(key[..KEYLEN].as_ref().into()),
        2 => Aes256GcmSiv::new(key[..KEYLEN].as_ref().into()),
        _ => {}
    };
// `match` arms have incompatible types

    let mut stream_encryptor=stream::EncryptorBE32::from_aead(aead, &nonce.into());

```
This is not related to RustCrypto but if anyone have a simple good example... The full encryption code is [here](https://github.com/Antidote1911/cryptyrust/blob/master/core/src/crypto.rs)

**Comment by brxken128** [comment]
I'm currently in the same boat, and have resorted to just copy/pasting the whole function.

@zer0x64 that doesn't work as the `Aead` doesn't implement `vtable` - well at least that was one of the errors I experienced.

@tarcieri do you have any clue on how one would go about doing this? I've tried reading through the `aead` crate but I can't quite wrap my head around it.

**Comment by brxken128** [comment]
I've tried doing everything under the sun - from wrapping it in an enum to `Box<>`ing it, nothing will work.

The closest I got was to wrap them in
```rust
pub enum StreamCiphers<A, C> {
    AESGCM { stream: A },
    CHACHA { stream: C },
}
```
and use a match statement to return them, but it had lifetime issues when mutable and it was just a bit cumbersome. I have zero clue where to go from here rip.

Any help would be **greatly** appreciated!

**Comment by brxken128** [comment]
@Antidote1911 I have figured out a way to do it (with the help from a few others).

You can find most of my solution in the `chacha` branch of my tool, Dexios.

[global.rs](https://github.com/brxken128/dexios/blob/chacha/src/global.rs) contains most of it, but you will also find the rest in [src/encrypt/crypto.rs](https://github.com/brxken128/dexios/blob/chacha/src/encrypt/crypto.rs) and [src/decrypt/crypto.rs](https://github.com/brxken128/dexios/blob/chacha/src/decrypt/crypto.rs).

Decrypting does not work for some reason, but the implementation itself should not break that (I don't think). I'd advise waiting a little while to allow me to iron out the quirks, but you can see [this issue](https://github.com/brxken128/dexios/issues/3) for more information about it.

**Comment by Antidote1911** [comment]
Oh ! Thank you very much, I look that. Ps, I have already forked Dexios for some time for study/inspiration ;)

**Comment by tarcieri** [comment]
I'd recommend an `enum`-based approach for this, although if you do that you should also wrap up handling of nonces as well (i.e. generating and prepending them to the message), since you've chosen two constructions with different nonce sizes, which will make things more complicated.

I wouldn't expect there to be any lifetime issues: both types are owned and otherwise use the same lifetimes. Please post a concrete example if you're still having issues.
