### ISSUE TITLE
chacha20poly1305 - XNonce causing a panic

### ISSUE THREAD

**Issue by brxken128** [RustCrypto/AEADs#425]
While using the latest v0.9.0 version of `chacha20poly1305`, I get odd panics while using XNonce as opposed to just handling the bytes directly.

I have this bit of code:

```rust
let nonce_bytes = StdRng::from_entropy().gen::<[u8; 20]>(); // 20 bytes to account for the LE31 part
let nonce = XNonce::from_slice(&nonce_bytes);

let (key, salt) = gen_key(raw_key)?;
let cipher = XChaCha20Poly1305::new_from_slice(key.expose_secret()).unwrap();

let mut stream = chacha20poly1305::aead::stream::EncryptorLE31::from_aead(cipher, nonce);
```

And I get panics related to `generic-array`, e.g.
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `24`,
 right: `20`', /home/broken/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.5/src/lib.rs:559:9
```

Changing to a 24 byte nonce gives a panic, with `left: 20` and `right: 24`.

I have got around this by doing this, but I'm still confused as to why it was happening in the first place.

```rust
let nonce_bytes = StdRng::from_entropy().gen::<[u8; 20]>(); // 20 bytes to account for the LE31 part

let (key, salt) = gen_key(raw_key)?;
let cipher = XChaCha20Poly1305::new_from_slice(key.expose_secret()).unwrap();

let mut stream = chacha20poly1305::aead::stream::EncryptorLE31::from_aead(cipher, nonce_bytes.as_slice().into());
```

**Comment by brxken128** [comment]
I believe it's worth noting that this exact thing worked with `aes-gcm`, which is why I don't think it should be happening.

**Comment by Antidote1911** [comment]
I think XNonce must be 24 bytes because it is intented to use with XChaCha20Poly1305 standard encryption. Not in stream mode where it must be 20.

**Comment by brxken128** [comment]
> I think XNonce must be 24 bytes because it is intented to use with XChaCha20Poly1305 standard encryption. Not in stream mode where it must be 20.

I thought this as well, but the generic `Nonce` type used with AES-GCM's stream encryption works for both streaming and non-streaming options.

**Comment by brxken128** [comment]
> I think XNonce must be 24 bytes because it is intented to use with XChaCha20Poly1305 standard encryption. Not in stream mode where it must be 20.

This was correct - thank you.

Apologies for opening this issue when it was evidently not needed.
