### ISSUE TITLE
Replace generic-array with const generics

### ISSUE THREAD

**Issue by conorbros** [RustCrypto/AEADs#429]
Coming back to this comment, is it feasible yet to replace `generic-array` with const generics yet?

>Longer term we will eventually replace `generic-array` with const generics so the error messages are much better, but it's not quite powerful enough for us to do so yet.

_Originally posted by @tarcieri in https://github.com/RustCrypto/AEADs/issues/353#issuecomment-900709267_

**Comment by newpavlov** [comment]
See the tracking issue for migrating from `generic-array`: https://github.com/RustCrypto/traits/issues/970
