### ISSUE TITLE
Key from slice breaks in aes-gcm-0.10.1

### ISSUE THREAD

**Issue by Ontokrat** [RustCrypto/AEADs#471]
Hello,

The following code in `aes-gcm-0.9.4`, to generate a cipher from a known key, now breaks in `aes-gcm-0.10.1`.
>let cipher = Aes256Gcm::new(Key::from_slice(key.as_ref()));

`key` is a byte string, like `b"a key"`.

The error is:
>type annotations needed: cannot satisfy `<_ as aes_gcm::KeySizeUser>::KeySize == aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UTerm, aes_gcm::aead::consts::B1>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>`
cannot satisfy `<_ as aes_gcm::KeySizeUser>::KeySize == aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UInt<aes_gcm::aead::generic_array::typenum::UTerm, aes_gcm::aead::consts::B1>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>, aes_gcm::aead::consts::B0>`

The doc in `aes-gcm-0.9.4`
>let key = Key::from_slice(b"an example very very secret key.");
let cipher = Aes256Gcm::new(key);

changed in `aes-gcm-0.10.1` for
>let key = Aes256Gcm::generate_key(&mut OsRng);
let cipher = Aes256Gcm::new(&key);

How in `aes-gcm-0.10.1` generate a key from a known byte string?

Thanks.

**Comment by tarcieri** [comment]
`Key` is generic around the cipher, and the compiler can’t infer the generic parameter.

Use `Key::<Aes256Gcm>::from_slice` instead.

**Comment by Ontokrat** [comment]
Thanks @tarcieri , perfect.

PR for the doc https://github.com/RustCrypto/AEADs/pull/472
