### ISSUE TITLE
Usage chacha20poly1305 doesn't compile

### ISSUE THREAD

**Issue by jpfreyen** [RustCrypto/AEADs#488]
This:

https://docs.rs/chacha20poly1305/latest/chacha20poly1305/index.html#usage-1

compiles and produces this ( would also be nice if the code was wrapped around a main() as well to make it even that more easy to work):

$ cargo build
   Compiling encrypt2_log v0.1.0 (/Users/phome/encrypt2_log)
warning: unused import: `XNonce`
 --> src/main.rs:3:24
  |
3 |     XChaCha20Poly1305, XNonce
  |                        ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`)
  --> src/main.rs:10:75
   |
6  | / fn main() {
7  | |     let key = XChaCha20Poly1305::generate_key(&mut OsRng);
8  | |     let cipher = XChaCha20Poly1305::new(&key);
9  | |     let nonce = XChaCha20Poly1305::generate_nonce(&mut OsRng); // 192-bits; unique per message
10 | |     let ciphertext = cipher.encrypt(&nonce, b"plaintext message".as_ref())?;
   | |                                                                           ^ cannot use the `?` operator in a function that returns `()`
...  |
13 | |
14 | | }
   | |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `FromResidual<Result<Infallible, chacha20poly1305::Error>>` is not implemented for `()`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`)
  --> src/main.rs:11:64
   |
6  | / fn main() {
7  | |     let key = XChaCha20Poly1305::generate_key(&mut OsRng);
8  | |     let cipher = XChaCha20Poly1305::new(&key);
9  | |     let nonce = XChaCha20Poly1305::generate_nonce(&mut OsRng); // 192-bits; unique per message
10 | |     let ciphertext = cipher.encrypt(&nonce, b"plaintext message".as_ref())?;
11 | |     let plaintext = cipher.decrypt(&nonce, ciphertext.as_ref())?;
   | |                                                                ^ cannot use the `?` operator in a function that returns `()`
12 | |     assert_eq!(&plaintext, b"plaintext message");
13 | |
14 | | }
   | |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `FromResidual<Result<Infallible, chacha20poly1305::Error>>` is not implemented for `()`

For more information about this error, try `rustc --explain E0277`.
warning: `encrypt2_log` (bin "encrypt2_log") generated 1 warning
error: could not compile `encrypt2_log` due to 2 previous errors; 1 warning emitted
jntel-macbook:phome/encrypt2_log ‹master*›$ 

==== stats ====

rustc 1.62.0 (a8314ef7d 2022-06-27)

chacha20poly1305 = "0.10.1"

**Comment by tarcieri** [comment]
The compiler is telling you the problem here:

> error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` 

You need to return a `Result` from the function you are invoking the example code from. For `fn main`, that looks something like:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    [...]
}
```
