### ISSUE TITLE
'alloc' doesn't seem to work correctly

### ISSUE THREAD

**Issue by Mercanuis** [RustCrypto/AEADs#492]
Hello
I'm helping with an intern project to try and experiment with AES-GCM-SIV on AEADs

The [documentation](https://docs.rs/aes-gcm-siv/0.11.1/aes_gcm_siv/#in-place-usage-eliminates-alloc-requirement) states:

> This crate has an optional alloc feature which can be disabled in e.g. microcontroller environments that don’t have a heap.
> 
> The [AeadInPlace::encrypt_in_place](https://docs.rs/aes-gcm-siv/0.11.1/aes_gcm_siv/trait.AeadInPlace.html#method.encrypt_in_place) and [AeadInPlace::decrypt_in_place](https://docs.rs/aes-gcm-siv/0.11.1/aes_gcm_siv/trait.AeadInPlace.html#method.decrypt_in_place) methods accept any type that impls the [aead::Buffer](https://docs.rs/aead/0.5.0/x86_64-unknown-linux-gnu/aead/trait.Buffer.html) trait which contains the plaintext for encryption or ciphertext for decryption.
> 
> Note that if you enable the heapless feature of this crate, you will receive an impl of [aead::Buffer](https://docs.rs/aead/0.5.0/x86_64-unknown-linux-gnu/aead/trait.Buffer.html) for heapless::Vec (re-exported from the [aead](https://docs.rs/aead/0.5.0/x86_64-unknown-linux-gnu/aead/index.html) crate as [aead::heapless::Vec]), which can then be passed as the buffer parameter to the in-place encrypt and decrypt methods:

However, this doesn't seem to work, and building seems to set up an issue with the building of the buffer per the documentation's example

```
 ~/Workspaces/josekit-rs/ [xxx/test-1*] cargo build
    Blocking waiting for file lock on build directory
   Compiling josekit v0.8.1 (/Users/xxx/Workspaces/josekit-rs)
error[E0432]: unresolved import `aes_gcm_siv::heapless`
 --> src/jwe/enc/aesgcmsiv_v1.rs:6:19
  |
6 | use aes_gcm_siv::{heapless::Vec, Aes128GcmSiv, KeyInit, Nonce, Tag as SivTag};
  |                   ^^^^^^^^ could not find `heapless` in `aes_gcm_siv`
error[E0747]: constant provided when a type was expected
   --> src/jwe/enc/aesgcmsiv_v1.rs:100:45
    |
100 |                     let mut buffer: Vec<u8, 128> = Vec::new();
    |                                             ^^^

error[E0747]: constant provided when a type was expected
   --> src/jwe/enc/aesgcmsiv_v1.rs:143:45
    |
143 |                     let mut buffer: Vec<u8, 128> = Vec::new();
    |                                             ^^^
```

This is despite having the feature enabled
```
[dependencies]
thiserror = "1"
anyhow = "1"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
base64 = "0.13"
flate2 = "1"
openssl = "0.10.38"
time = "0.3"
aes-gcm-siv = { version = "0.11.1", features = ["alloc"] }
aes-gcm = "0.10.1"
aes = "0.8.2"
aead = "0.5.1"
```

### Workaround

To work around this, I referred to https://github.com/RustCrypto/AEADs/issues/88 and https://github.com/RustCrypto/AEADs/issues/398 and added the following crate (which, no offense sounds really sketchy)

```
chacha20poly1305 = { version = "0.9.0", default-features = false, features = ["heapless"] }

//in the code
use chacha20poly1305::aead::heapless::Vec;
```

This allowed me to at least fix the error, and any normal `Vec` were able to be fixed using full declaration `std::vec::Vec`

This seems like an issue, and I would like to ask for some clarification
* How do I pull in the `alloc` feature correctly?
* If not, can the documentation reflect this more correctly to avoid the `constant` issue?

Thank you for your consideration :)

**Comment by newpavlov** [comment]
You only enabled the `alloc` feature, while the `heapless` functionality requires the `heapless` feature to be enabled as well. It's directly stated in the cited docs:
>Note that if you enable the heapless feature of this crate

In other words, you should use:
```
aes-gcm-siv = { version = "0.11.1", features = ["alloc", "heapless"] }
```

**Comment by Mercanuis** [comment]
I see, so I just didnt' see that upon repeated readings. This is on me, thank you for this. I'll take another crack at it
