### ISSUE TITLE
Question: How to safely increment Nonces?

### ISSUE THREAD

**Issue by DRKSLV** [RustCrypto/AEADs#494]
Hey, this might be a bit of a dumb question but:
i want to encrypt multiple quite large byte slices, and increment the nonce in between the two calls...
since reusing a (key, nonce) is very dangerous.

i was wondering? can i just literally increment the value by one? or does the library split my byte slices into blocks, for which the nonce is also incremented, requiring me to increment the value by at least the amount of blocks in a slice?

or should i use a random one every time? that doesn't really feel safer though... i mean it would be technically possible for a value to repeat randomly.

uh is there a good approach for this? e.g an abstraction that promises me safety? 
or can you explain how the nonces are handled internally? whhich guarantees does my code need to enforce for these values, exactly?

there is a possibility i am overthinking this and the value just has to be unique between calls but...
uh better safe then sorry
i'd be thankful if someone could briefly answer... it was hard to find anything on this topic since it's kind of implementation specific / a stupid question

**Comment by DRKSLV** [comment]
Reading a little bit more into it...
It's on a per-call basis, right?
And i don't have to worry about the actual blocks of the encryption, because they chain into each other so to speak?

**Comment by tarcieri** [comment]
Take a look at https://docs.rs/aead/latest/aead/stream/index.html (which could probably use some better documentation)

It uses a combination of randomness and an incrementing counter for the nonce, although it can also be nice to bolster that with a per-STREAM key (derived using e.g. HKDF)

**Comment by DRKSLV** [comment]
Thank you, that's a good lead to follow!

**Comment by newpavlov** [comment]
As far as I know, using counter for nonces with AEAD algorithms is perfectly fine. If you can guarantee that key does not get reused (for example, if you work with ephemeral keys) you even can start the counter with 0. If you can not guarantee it, then you should initialize the counter with random value. You can read this [blog post](https://blog.cloudflare.com/tls-nonce-nse/) to learn how TLS handles nonces.

But note that you can not use counter for nonce/IV with stream ciphers, since they usually simply increment IV to generate next keystream block.

**Comment by DRKSLV** [comment]
@newpavlov 
So you mean that i can use a counter if i am the one in charge of the blocks, using aes_gcm::AeadInPlace::encrypt_in_place directly

But when i create a stream with:
aead::stream::StreamLE31::new

It is the one making blocks and incrementing the nonce, so i cant initialize two with the same key, and nonces that are close to each other

That would make... a lot of sense

**Comment by DRKSLV** [comment]
I think my first implementation of my wierd encryption tool does reuse a nonce currently

In the dumbest way possible
So i'm glad i took the time to think through it again

**Comment by DRKSLV** [comment]
(thank you! sry i forgot to close this)
