### ISSUE TITLE
reusing Aes256GcmSiv

### ISSUE THREAD

**Issue by bobi6666** [RustCrypto/AEADs#499]
good day, I would like to ask, is it safe to initialize Aes256GcmSiv at the top of fn main and then use it during the entire program run? or reinitialize it all the time when I need it?

**Comment by tarcieri** [comment]
Yes, you can reuse the instance. The nonce should be different every time however (though the construction will tolerate nonce reuse due to e.g. bugs without catastrophically collapsing, you still shouldn't reuse nonces deliberately)

**Comment by bobi6666** [comment]
and I don't have to worry that a leak can be used on the saved
instance? also I know that I should have used different nonces but it
is not always easy, for example while using udp packets

2023-01-10 14:57 GMT+01:00, Tony Arcieri ***@***.***>:

**Comment by bobi6666** [comment]
it is not enough to generate random nonce at the beginning on the
server and lets clients know this nonce? my friend told me:
GCM is supposed to let you only need to call random once to initialize
it and then you can count from there, maybe involving fastrand IDK,
the encrypt function should give you a nonce I thought.
also when i wanted to genrate random nonce and tell that to client in
some encrypted way he told: If you call rand too many times you can
exhaust the entropy pool, especially on the server
If it's called with every packet? It might.
Part of the entropy pool is generated from user input, so the clients
should be fine, but not the server. And if you exhaust the entropy
pool, either it will block until it has sufficient entropy, or it
starts degrading its randomness

2023-01-10 17:34 GMT+01:00, Tony Arcieri ***@***.***>:

**Comment by tarcieri** [comment]
The nonce for every packet needs to be unique.

You can use a counter alone for this purpose. It doesn't have to be random.

**Comment by bobi6666** [comment]
do you think i can find some example on how to do that properli? i
making that for audiogame for blind and i would like to be safe as
much as possible

2023-01-10 18:32 GMT+01:00, Tony Arcieri ***@***.***>:

**Comment by tarcieri** [comment]
WireGuard and its usage of the Noise protocol for UDP packet encryption is probably the best extant reference

**Comment by bobi6666** [comment]
can you provide some link to find that?

2023-01-10 18:37 GMT+01:00, Tony Arcieri ***@***.***>:

**Comment by tarcieri** [comment]
https://www.wireguard.com/protocol/
