### ISSUE TITLE
aes-gcm partial tag

### ISSUE THREAD

**Issue by ALaggyDev** [RustCrypto/AEADs#500]
Hi,
I am trying to use the `gcm` crate but with a 12 byte authorization tag, instead of the standard 16 byte authorization tag.
I can't really decrypt data because the program only know the first 12 byte tag.

According to online documentation, tag size can be customized in aes/gcm (by using the leftmost bytes).
So I am wondering if there is a possibility of implementing custom tag size in the `gcm` crate.
Thanks!

**Comment by tarcieri** [comment]
We can make tag length a generic parameter like nonce size is, although that will be a breaking change.

Per [NIST SP 800-38D](https://csrc.nist.gov/publications/detail/sp/800-38d/final) Appendix C, the only allowed sizes are 96, 104, 112, 120 or 128, so we'll need a marker trait for the tag size to bless those particular sizes as acceptable.

**Comment by ALaggyDev** [comment]
Is making tag lengh generic parameter really a breaking change if we set a default generic type?

Can something like this work?
```rust
/// AES-GCM tags.
pub type Tag<TagSize = U16> = GenericArray<u8, TagSize>;

pub struct AesGcm<Aes, NonceSize, T = U16>
where T: TagSize { ... }

// Implement for U8, U12, U13, U14, U15, U16
pub trait TagSize {}
```

Every new generic parameter have a default type, so I think it's fine?

**Comment by tarcieri** [comment]
IIRC we tried that with `NonceSize` and ran into problems, although I don't remember what they were offhand.

Feel free to attempt it and open a PR (although if you do, please use something more descriptive than `T` as the generic parameter name)

**Comment by dmitry-zakablukov** [comment]
@tarcieri , can you please publish a new version of `aes-gcm` package with variable TagSize? I really need these changes in my code.

**Comment by tarcieri** [comment]
Done: #530

**Comment by dmitry-zakablukov** [comment]
@tarcieri , thank you!
