### ISSUE TITLE
required features for CCM on MCU

### ISSUE THREAD

**Issue by StefanHri** [RustCrypto/AEADs#502]
I want to use ccm on a microcontroller (`thumbv8m.main-none-eabi` ) with `#![no_std]`. In my `Cargo.toml` I specified: `ccm = { version = "0.5.0", default-features = false, features = ["heapless"] }`. With this configuration I am getting:
```
error[E0432]: unresolved imports `ccm::aead::Aead`, `ccm::aead::Payload`
 --> src/crypto_wrapper.rs:3:41
  |
3 |     aead::{generic_array::GenericArray, Aead, KeyInit, Payload},
  |                                         ^^^^           ^^^^^^^ no `Payload` in the root
  |                                         |
  |                                         no `Aead` in the root

error[E0599]: no method named `encrypt` found for struct `Ccm` in the current scope
  --> src/crypto_wrapper.rs:57:22
   |
57 |     let res = cipher.encrypt(nonce_internal, plaintext).unwrap();
   |                      ^^^^^^^ method not found in `Ccm<Aes128, UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>, B1>>`

error[E0599]: no method named `decrypt` found for struct `Ccm` in the current scope
  --> src/crypto_wrapper.rs:77:22
   |
77 |     let res = cipher.decrypt(nonce_internal, ciphertext).unwrap();
   |                      ^^^^^^^ method not found in `Ccm<Aes128, UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>, B1>>`
```
If I use only `ccm = "0.5.0"` and build for my Linux host the code works as expected.

Which features do I need to turn on to get it running on `thumbv8m.main-none-eabi` MCU?

**Comment by tarcieri** [comment]
The `Aead` trait requires `alloc`: https://docs.rs/aead/latest/aead/trait.Aead.html

> Available on *crate feature* `alloc` only

You need to use the `AeadInPlace` trait. Unfortunately we don't have a ready-made code example for the `ccm` crate, but you can look at the `aes_gcm` crate for a similar example:

https://docs.rs/aes-gcm/latest/aes_gcm/#in-place-usage-eliminates-alloc-requirement
