### ISSUE TITLE
noob authenticate unencrypted data

### ISSUE THREAD

**Issue by fhhowdy** [RustCrypto/AEADs#504]
I'm working with some data in which I have the public key and I'm trying to calculate the aes-gcm mac for the data for validation.  

The catch is that the data is not encrypted -- they're using aes-gcm for signing only, as it's important to have the data open (i.e. there is an explicit need for no secrecy, but also an explicit need for authenticity).

With that as a background, all of the solutions I've seen assume you're working with encrypted data.  I've looked at the decrypt and decrypt in place functions, which appear to be a great framework for what I'm trying to do, but I don't want to actually apply the decryption.   Before I go an completely mis-use the library or write my own function to do this, I thought I would ask to see if anyone has had a similar use-case, and if so, could you point me in the right direction so I can learn the proper way to do this?

Thanks in advance.

**Comment by tarcieri** [comment]
There are two ways to do authentication only (without encryption) using GCM:

- Additional authenticated data (AAD): optional data to be authenticated via AES-GCM, but not encrypted 
- GMAC: this is a MAC built on GCM. It is rarely used and we don't currently support it

The first step is figuring out which of these constructions they're using

**Comment by fhhowdy** [comment]
They are using the first method.  There is no data in the AEAD section.  All of it is in the AAD, thus resulting in just the hash.

**Comment by fhhowdy** [comment]
Thank you for the help!  That worked like a charm!!
