### ISSUE TITLE
Fix or disable codecov CI job

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/AEADs#508]
Currently it [fails](https://github.com/RustCrypto/AEADs/actions/runs/4293352682/jobs/7480920511) with the following error:
>Error: Couldn't find a release tarball containing binaries for latest

It does not look like https://github.com/actions-rs/tarpaulin has changed in any way. Maybe there are changes in GitHub API?

**Comment by tarcieri** [comment]
I'm fine with getting rid of it at this point
