### ISSUE TITLE
generic array / stream encryptor type mismatch

### ISSUE THREAD

**Issue by ousado** [RustCrypto/AEADs#542]
The following code
```rust
use chacha20poly1305::{
    aead::{stream, OsRng},
    XChaCha20Poly1305, XNonce, Key, KeyInit, AeadCore
};

fn main() {
    let key   : Key               = XChaCha20Poly1305::generate_key(&mut OsRng);
    let nonce : XNonce            = XChaCha20Poly1305::generate_nonce(&mut OsRng);
    let aead  : XChaCha20Poly1305 = XChaCha20Poly1305::new(&key);
    let stream_encryptor          = stream::EncryptorBE32::from_aead(aead,&nonce);
}
```
produces the following error:
```
error[E0308]: mismatched types
   --> src/main.rs:11:78
    |
11  |     let stream_encryptor             = stream::EncryptorBE32::from_aead(aead,&nonce);
    |                                        --------------------------------      ^^^^^^ expected `B0`, found `B1`
    |                                        |
    |                                        arguments to this function are incorrect
    |
    = note: expected reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B1>, B1>>`
               found reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>, B0>, B0>>`
note: associated function defined here
   --> / .. .. .. /cargo/registry/src/index.crates.io-6f17d22bba15001f/aead-0.5.2/src/stream.rs:337:1
    |
337 | / impl_stream_object!(
338 | |     Encryptor,
339 | |     encrypt_next,
340 | |     encrypt_next_in_place,
...   |
346 | |     "ℰ STREAM encryptor"
347 | | );
    | |_^
    = note: this error originates in the macro `impl_stream_object` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Here's a repository with this example:
https://github.com/ousado/xcc20poly1305issue/blob/main/src/main.rs

**Comment by tarcieri** [comment]
The nonce size for `*BE32` is 5-bytes smaller (32-bit counter + last block flag byte than the 24-byte XChaCha20Poly1305 nonce so 24 - 5 = 19 bytes

**Comment by ousado** [comment]
I assumed it's somehow generic over the cipher's NonceSize due to these definitions: 

pub type Nonce<A, S> = [GenericArray](https://docs.rs/generic-array/0.14.7/x86_64-unknown-linux-gnu/generic_array/struct.GenericArray.html)<[u8](https://doc.rust-lang.org/nightly/std/primitive.u8.html), [NonceSize](https://docs.rs/aead/latest/aead/stream/type.NonceSize.html)<A, S>>; 

pub type NonceSize<A, S> = <<A as [AeadCore](https://docs.rs/aead/latest/aead/trait.AeadCore.html)>::[NonceSize](https://docs.rs/aead/latest/aead/trait.AeadCore.html#associatedtype.NonceSize) as [Sub](https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html)<<S as [StreamPrimitive](https://docs.rs/aead/latest/aead/stream/trait.StreamPrimitive.html)<A>>::[NonceOverhead](https://docs.rs/aead/latest/aead/stream/trait.StreamPrimitive.html#associatedtype.NonceOverhead)>>::[Output](https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html#associatedtype.Output);

Does that mean there is currently no stream::Encryptor that can be used with XChaCha20Poly1305?

**Comment by tarcieri** [comment]
No, it just means you're passing the wrong nonce size.

You need to use `GenericArray<u8, U19>`.

You can use those type aliases if you'd like, but right now you're using `XNonce` which is 24-byte.

**Comment by ousado** [comment]
Ah, I see, thanks for the quick clarification!
