### ISSUE TITLE
Bump dependency on generic-array to version 1.0.0

### ISSUE THREAD

**Issue by schoenenberg** [RustCrypto/AEADs#553]
Hi,

I have noticed that the _generic-array_ crate has released version [`1.0.0`](https://github.com/fizyk20/generic-array/releases/tag/1.0.0). Can we bump the dependency of the `aes-gcm-siv` crate?

**Comment by tarcieri** [comment]
We're migrating to `hybrid-array` in the next release. You can follow along here:

https://github.com/RustCrypto/traits/pull/1319
