### ISSUE TITLE
Using streamed data with ChaCha20Poly1305

### ISSUE THREAD

**Issue by pfz4** [RustCrypto/AEADs#561]
Hello,
I want to encrypt a stream using ChaCha20Poly1305.
`chacha20` does supply the `apply_keystream` function to encrypt streamed data.
I can't find a alternative to that using ChaCha20Poly1305.
As far as I can tell you have to supply the whole plain-/ciphertext loaded in memory.

How could I encrypt data that is larger that the available memory in my machine?

Am I missing something?

Cheers,
Paul

**Comment by newpavlov** [comment]
Right now it's not possible without manually using the underlying primitives. See https://github.com/RustCrypto/traits/issues/1364 for more information.

**Comment by pfz4** [comment]
Thanks
