### ISSUE TITLE
Support for nonce omission in AES-SIV

### ISSUE THREAD

**Issue by matthew-levan** [RustCrypto/AEADs#569]
https://datatracker.ietf.org/doc/html/rfc5297#section-4

**Comment by tarcieri** [comment]
This can be accomplished by using the AEAD interface with a fixed nonce, or using [`aes::siv::Siv`](https://docs.rs/aes-siv/latest/aes_siv/siv/struct.Siv.html) (or one of its aliases) which provides access to the raw SIV interface, where you can pass an empty or fixed set of headers.

**Comment by matthew-levan** [comment]
Thanks @tarcieri that works for me. Is there support for 48-byte keys?

**Comment by tarcieri** [comment]
Not currently

**Comment by matthew-levan** [comment]
> Not currently

I used this @tarcieri and it works:
```
use aes::Aes192;
type Aes192Siv = CmacSiv<Aes192>;
```
