### ISSUE TITLE
Consider exposing AesGcm::compute_tag

### ISSUE THREAD

**Issue by bryceberger** [RustCrypto/AEADs#586]
(and, to make it usable, `AesGcm::init_ctr()`)

It is useful to be able to generate a hash without caring about the encrypted text, and it would be nice to just use the implementations in the aes_gcm crate directly.

**Comment by newpavlov** [comment]
Do you mean GMAC? It's better to introduce a separate crate for it in the [MACs repository](https://github.com/RustCrypto/MACs).

**Comment by tarcieri** [comment]
GMAC is an option, although you can also get similar properties out of AES-GCM itself by using an empty plaintext/ciphertext and passing only the additional associated data to be authenticated

**Comment by newpavlov** [comment]
Going to close this in favor of https://github.com/RustCrypto/MACs/issues/1
