### ISSUE TITLE
`bytes` feature of `aead` is not re-exported by AEADs

### ISSUE THREAD

**Issue by davepollack** [RustCrypto/AEADs#600]
Hi,

I have a `BytesMut` given to me by `quinn-proto`, that I would like to use as a `Buffer` with `chacha20poly1305`. The impl of `Buffer` for `BytesMut` is gated behind the `bytes` feature.

However I cannot specify `features = ["bytes"]` with `chacha20poly1305`, as its Cargo.toml (and I think other AEADs) does not re-export the feature. This seems to be inconsistent with other similar features like `heapless` and `arrayvec` that are re-exported.

Currently I've added `aead` with `features = ["bytes"]` to my Cargo.toml to union in the feature, which isn't too bad, but I'm wondering if this is an oversight.

Cheers

**Comment by tarcieri** [comment]
Yeah, we can potentially add passthroughs for this like we have for `heapless`
