### ISSUE TITLE
how to use diffrent length sample data

### ISSUE THREAD

**Issue by gzbakku** [RustCrypto/AEADs#61]
hey man i've tried everything but i still can t use any string other then "plaintext message" as bytes i am guessing it have something to do with block size of 128 bits and padding but please can you help my goal if to encrypt any length of message.

**Comment by tarcieri** [comment]
Which crate are you attempting to use?

**Comment by gzbakku** [comment]
thanks man i found the solution i was not using correct length of key and nonce thanks for making this crate you are awesome.
