### ISSUE TITLE
Get NonceSize from the algorithm

### ISSUE THREAD

**Issue by tisonkun** [RustCrypto/AEADs#622]
Is it reasonable to add a method `nonce_size()` to algorithms like `Aes256Gcm`?

Usage:

```
let nonce_size = Aes256Gcm::nonce_size();
```

To avoid inline magic numbers (12 in this case).

**Comment by tarcieri** [comment]
Nonce size is available as [`AeadCore::NonceSize`](https://docs.rs/aead/latest/aead/trait.AeadCore.html#associatedtype.NonceSize).

The [`typenum::Unsigned::USIZE`](https://docs.rs/typenum/1.16.0/typenum/marker_traits/trait.Unsigned.html#associatedconstant.USIZE) associated constant in particular can be used to query it as a `usize`.

**Comment by tisonkun** [comment]
@tarcieri Yeah. I can see the `NonceSize` associated type. In what syntax I can get the size from the `Aes256Gcm` type or an instant of it?

**Comment by tarcieri** [comment]
```rust
<Aes256Gcm as AeadCore>::NonceSize::USIZE
```

**Comment by tisonkun** [comment]
@tarcieri Thank you! Works perfectly:

```rust
use aes_gcm::aead::Aead;
use aes_gcm::aes::cipher::Unsigned;
use aes_gcm::AeadCore;

let nonce_size = <aes_gcm::Aes256Gcm as AeadCore>::NonceSize::USIZE;
```
