### ISSUE TITLE
AES-256 generating a 64 byte key?

### ISSUE THREAD

**Issue by thomasmost** [RustCrypto/AEADs#624]
Hi, I'm developing a protocol that requires interoperability between clients written in different languages using the AES encryption algorithm. Our first clients were in Rust, and I'm working on a Java implementation now. Basically we want a Java client to be able to encrypt a payload, send it to the Rust client, and have the Rust client decrypt it. Not rocket science.

In the process of testing, I'm generating a key in Rust, like so:
```rs

pub fn generate_key() -> Vec<u8> {
  let bytekey = Aes256SivAead::generate_key(&mut OsRng);
  bytekey.to_vec()
}

```

...but when I try to use this key to decrypt in Java, I get this error:
`Invalid AES key length: 64 bytes`

Sure enough... it looks like the `bytekey` vector length (Vec<u8>) is 64. I would have expected it to be 32! Can someone help me understand what I'm missing?

Potentially relevant: I'm base64 encoding the key rather than sending it as raw bytes

**Comment by tarcieri** [comment]
AES-SIV uses keys which are twice the size of the corresponding AES key.

Are you sure you're actually using AES-SIV on the Java side of things?

**Comment by thomasmost** [comment]
That sounds like the missing piece! Thanks very much @tarcieri

**Comment by tarcieri** [comment]
Also note that AES-SIV is largely obsoleted by AES-GCM-SIV

**Comment by thomasmost** [comment]
got it, I'll migrate the services to that
