### ISSUE TITLE
aes-gcm: Link to NCC Group audit goes to a 404: Not found page

### ISSUE THREAD

**Issue by rmg-x** [RustCrypto/AEADs#634]
Hi, the audit link in the aes-gcm README currently 404s:
https://github.com/RustCrypto/AEADs/blob/ad456ad32930ee2cc58e466478fe757822c22f7f/aes-gcm/README.md?plain=1#L60

The only working page I can find is this, but the PDF download there also 404s:
https://www.nccgroup.com/us/research-blog/public-report-rustcrypto-aesgcm-and-chacha20pluspoly1305-implementation-review/

**Comment by rmg-x** [comment]
I was able to find it on the internet archive if anyone is interested:

https://web.archive.org/web/20240108154854/https://research.nccgroup.com/wp-content/uploads/2020/02/NCC_Group_MobileCoin_RustCrypto_AESGCM_ChaCha20Poly1305_Implementation_Review_2020-02-12_v1.0.pdf

**Comment by tarcieri** [comment]
Ugh, yes, NCC annoyingly seems to have removed all of the audits from their web site.

Fixed in 989f554
