### ISSUE TITLE
Chacha20poly1305 versions after and including 0.11.0-pre.1 require alloc on no_std.

### ISSUE THREAD

**Issue by ionspin** [RustCrypto/AEADs#643]
`chacha20poly1305 = { version = "0.11.0-pre.1", default-features = false, features = [] }`

Build result:

```
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait
```

`chacha20poly1305 = { version = "0.10.1", default-features = false, features = [] }` builds successfuly.

I might be missing something obvious, it's late here :)

**Comment by tarcieri** [comment]
My best guess is `chacha20poly1305` has a hard requirement for `chacha20/zeroize`, and it looks like `chacha20` is pulling `zeroize` in without `default-features = false`, which is linking liballoc

**Comment by newpavlov** [comment]
>chacha20poly1305 has a hard requirement for chacha20/zeroize

But why is it a hard requirement? Most other crates have _optional_ support for zeroize.

>chacha20 is pulling zeroize in without default-features = false

Yeah, the problem is [here](https://github.com/RustCrypto/stream-ciphers/blob/master/chacha20/Cargo.toml#L26).

**Comment by tarcieri** [comment]
It was likely introduced in recent changes. I’m on a phone so I would suggest using the git history to answer your question.

**Comment by newpavlov** [comment]
Hm, it looks like `zeroize` was an unconditional dependency since v0.1 times. I guess it was an oversight, which did not get noticed later.
