### ISSUE TITLE
aes-gcm: Make `key_size()` a const fn

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [RustCrypto/AEADs#649]
I am trying to use [`key_size`](https://docs.rs/aes-gcm/latest/aes_gcm/trait.KeySizeUser.html#method.key_size) like this:
```rs
#[derive(Debug, Serialize, Deserialize)]
struct EncryptionData {
    password_derived_key_salt: [u8; Salt::RECOMMENDED_LENGTH],
    password_derived_key: [u8; Aes256Gcm::key_size()],
}
```
But that isn't currently possible:
```
cannot call non-const fn `<AesGcm<aes_gcm::aes::Aes256, UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>, B0>> as KeySizeUser>::key_size` in constants
calls in constants are limited to constant functions, tuple structs and tuple variants
```
It seems like `key_size` could be made const just by adding `const` to it.

**Comment by newpavlov** [comment]
Trait methods can not be currently made `const` on stable Rust. You should import the `Unsigned` trait and use `Aes256Gcm::KeySize::USIZE`.

**Comment by ChocolateLoverRaj** [comment]
I was using nightly a lot recently so I didn't realize. I will use the trait.

**Comment by nixpulvis** [comment]
Why does `aes_siv::siv::KeySize::<Aes256SivAead>::USIZE` return `128`?

**Comment by tarcieri** [comment]
Sure. It could probably use its own issue, as this is a closed issue for the `aes-gcm` crate
