### ISSUE TITLE
chacha20poly1305 is not no_std

### ISSUE THREAD

**Issue by nickray** [RustCrypto/AEADs#88]
Hey

It seems that somehow the `alloc` feature is pulled in even when it's disabled: Compiling https://github.com/nickray/chacha8poly1305-test (which I believe is using the library as intended) results in

```
% cargo build --target thumbv7em-none-eabi                 :(
   Compiling chacha20poly1305 v0.3.3
   Compiling chacha8poly1305-test v0.1.0 (/home/nicolas/projects/RustCrypto/chacha8poly1305-test)
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait.                                                                                                                    

error: `#[alloc_error_handler]` function required, but not found

error: aborting due to 2 previous errors

error: could not compile `chacha8poly1305-test`.
```

I have not been able to track this down so far unfortunately.

**Comment by tarcieri** [comment]
It seems while we test for building without `std`, we're not properly testing we build without `alloc`. I'll open a separate issue about that.

I managed to trace it down: the `chacha20` crate's `zeroize` feature isn't setting `default-features = false`:

https://github.com/RustCrypto/stream-ciphers/blob/10d170c/chacha20/Cargo.toml#L25

This is enabled unilaterally by the `chacha20poly1305` crate, so there's no workaround other than fixing the `chacha20` crate. I'll try to put out another release later today.

**Comment by nickray** [comment]
Perfect, that's it. Thanks!

First time I had an `alloc` issue; testing for it is a bit insidious as the library itself compiles, only a binary using it fails to link.

Now to finally make good use of your Chacha8Poly1305 :)

**Comment by tarcieri** [comment]
`chacha20` v0.3.4 is out with https://github.com/RustCrypto/stream-ciphers/pull/105
